version: "3.8"
name: "todoo-app"
services:
  react-app:
    container_name: ToDoo-WebApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - react-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  react-network:
    driver: bridge

volumes:
  node_modules: